// Code generated by the Lingua Franca compiler from:
// file:/c:/Users/Amin/Desktop/RT/project/sender-receiver-LF/src/senderreceiver.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "4", "sec" };
void lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "_bitgenerator.h"
#include "_sendermodel.h"
#include "_receivermodel.h"
#include "_senderreceiver_main.h"
typedef enum {
    senderreceiver_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&envs[senderreceiver_main],"senderreceiver",senderreceiver_main,_lf_number_of_workers,1,2,2,0,5,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _senderreceiver_main_main_self_t* senderreceiver_main_self[1];
    SUPPRESS_UNUSED_WARNING(senderreceiver_main_self);
    _bitgenerator_self_t* senderreceiver_bitgenerator_self[1];
    SUPPRESS_UNUSED_WARNING(senderreceiver_bitgenerator_self);
    _sendermodel_self_t* senderreceiver_sender_self[1];
    SUPPRESS_UNUSED_WARNING(senderreceiver_sender_self);
    _receivermodel_self_t* senderreceiver_receiver_self[1];
    SUPPRESS_UNUSED_WARNING(senderreceiver_receiver_self);
    // ***** Start initializing senderreceiver of class senderreceiver
    senderreceiver_main_self[0] = new__senderreceiver_main();
    senderreceiver_main_self[0]->base.environment = &envs[senderreceiver_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    
    {
        _senderreceiver_main_main_self_t *self = senderreceiver_main_self[0];
        // ***** Start initializing senderreceiver.bitGenerator of class BitGenerator
        senderreceiver_bitgenerator_self[0] = new__bitgenerator();
        senderreceiver_bitgenerator_self[0]->base.environment = &envs[senderreceiver_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        senderreceiver_bitgenerator_self[0]->_lf_out_width = -2;
        { // For scoping
            static int _initial = 0;
            senderreceiver_bitgenerator_self[0]->sent = _initial;
        } // End scoping.
        // Initiaizing timer senderreceiver.bitGenerator.inputTimer.
        senderreceiver_bitgenerator_self[0]->_lf__inputTimer.offset = 0;
        senderreceiver_bitgenerator_self[0]->_lf__inputTimer.period = SEC(1);
        // Associate timer with the environment of its parent
        envs[senderreceiver_main].timer_triggers[timer_triggers_count[senderreceiver_main]++] = &senderreceiver_bitgenerator_self[0]->_lf__inputTimer;
        senderreceiver_bitgenerator_self[0]->_lf__inputTimer.mode = NULL;
    
        senderreceiver_bitgenerator_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing senderreceiver.bitGenerator
    }
    {
        _senderreceiver_main_main_self_t *self = senderreceiver_main_self[0];
        // ***** Start initializing senderreceiver.sender of class SenderModel
        senderreceiver_sender_self[0] = new__sendermodel();
        senderreceiver_sender_self[0]->base.environment = &envs[senderreceiver_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        senderreceiver_sender_self[0]->_lf_up_width = -2;
        // width of -2 indicates that it is not a multiport.
        senderreceiver_sender_self[0]->_lf_down_width = -2;
        // width of -2 indicates that it is not a multiport.
        senderreceiver_sender_self[0]->_lf_in_width = -2;
        envs[senderreceiver_main].startup_reactions[startup_reaction_count[senderreceiver_main]++] = &senderreceiver_sender_self[0]->_lf__reaction_0;
        envs[senderreceiver_main].shutdown_reactions[shutdown_reaction_count[senderreceiver_main]++] = &senderreceiver_sender_self[0]->_lf__reaction_3;
        { // For scoping
            static int _initial[] = {1,0,0,1,1,0,1,0,0};
            senderreceiver_sender_self[0]->sequence = _initial;
        } // End scoping.
        { // For scoping
            static int _initial = 9;
            senderreceiver_sender_self[0]->length = _initial;
        } // End scoping.
        { // For scoping
            static int _initial = 0;
            senderreceiver_sender_self[0]->x = _initial;
        } // End scoping.
        senderreceiver_sender_self[0]->step = MSEC(100);
        { // For scoping
            static SenderModelState _initial = 0;
            senderreceiver_sender_self[0]->currState = _initial;
        } // End scoping.
        // Initializing action senderreceiver.sender.a
        senderreceiver_sender_self[0]->_lf__a.offset = 0;
        senderreceiver_sender_self[0]->_lf__a.period = -1;
        senderreceiver_sender_self[0]->_lf__a.last_tag = NEVER_TAG;
        senderreceiver_sender_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(senderreceiver_sender_self[0]->_lf__a),
        0);
        senderreceiver_sender_self[0]->_lf__a.status = absent;
        senderreceiver_sender_self[0]->_lf__reaction_0.deadline = NEVER;
        senderreceiver_sender_self[0]->_lf__reaction_1.deadline = NEVER;
        senderreceiver_sender_self[0]->_lf__reaction_2.deadline = NEVER;
        senderreceiver_sender_self[0]->_lf__reaction_3.deadline = NEVER;
        //***** End initializing senderreceiver.sender
    }
    {
        _senderreceiver_main_main_self_t *self = senderreceiver_main_self[0];
        // ***** Start initializing senderreceiver.receiver of class ReceiverModel
        senderreceiver_receiver_self[0] = new__receivermodel();
        senderreceiver_receiver_self[0]->base.environment = &envs[senderreceiver_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        senderreceiver_receiver_self[0]->_lf_up_width = -2;
        envs[senderreceiver_main].startup_reactions[startup_reaction_count[senderreceiver_main]++] = &senderreceiver_receiver_self[0]->_lf__reaction_0;
        envs[senderreceiver_main].shutdown_reactions[shutdown_reaction_count[senderreceiver_main]++] = &senderreceiver_receiver_self[0]->_lf__reaction_2;
        { // For scoping
            static int _initial = 0;
            senderreceiver_receiver_self[0]->y = _initial;
        } // End scoping.
        senderreceiver_receiver_self[0]->step = MSEC(100);
        { // For scoping
            static ReceiverModelState _initial = 0;
            senderreceiver_receiver_self[0]->currState = _initial;
        } // End scoping.
        // Initializing action senderreceiver.receiver.a
        senderreceiver_receiver_self[0]->_lf__a.offset = 0;
        senderreceiver_receiver_self[0]->_lf__a.period = -1;
        senderreceiver_receiver_self[0]->_lf__a.last_tag = NEVER_TAG;
        senderreceiver_receiver_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(senderreceiver_receiver_self[0]->_lf__a),
        0);
        senderreceiver_receiver_self[0]->_lf__a.status = absent;
        senderreceiver_receiver_self[0]->_lf__reaction_0.deadline = NEVER;
        senderreceiver_receiver_self[0]->_lf__reaction_1.deadline = NEVER;
        senderreceiver_receiver_self[0]->_lf__reaction_2.deadline = NEVER;
        //***** End initializing senderreceiver.receiver
    }
    //***** End initializing senderreceiver
    // **** Start deferred initialize for senderreceiver
    {
    
    
    
        // **** Start deferred initialize for senderreceiver.bitGenerator
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of senderreceiver.bitGenerator.
            senderreceiver_bitgenerator_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            senderreceiver_bitgenerator_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &senderreceiver_bitgenerator_self[0]->base.allocations);
            senderreceiver_bitgenerator_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &senderreceiver_bitgenerator_self[0]->base.allocations);
            senderreceiver_bitgenerator_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &senderreceiver_bitgenerator_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    senderreceiver_bitgenerator_self[0]->_lf__reaction_0.output_produced[count++] = &senderreceiver_bitgenerator_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of senderreceiver.bitGenerator
        
        }
        // **** End of deferred initialize for senderreceiver.bitGenerator
        // **** Start deferred initialize for senderreceiver.sender
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of senderreceiver.sender.
            senderreceiver_sender_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of senderreceiver.sender
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of senderreceiver.sender.
            senderreceiver_sender_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of senderreceiver.sender
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of senderreceiver.sender.
            senderreceiver_sender_self[0]->_lf__reaction_2.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            senderreceiver_sender_self[0]->_lf__reaction_2.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &senderreceiver_sender_self[0]->base.allocations);
            senderreceiver_sender_self[0]->_lf__reaction_2.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &senderreceiver_sender_self[0]->base.allocations);
            senderreceiver_sender_self[0]->_lf__reaction_2.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &senderreceiver_sender_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    senderreceiver_sender_self[0]->_lf__reaction_2.output_produced[count++] = &senderreceiver_sender_self[0]->_lf_up.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of senderreceiver.sender
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_4 of senderreceiver.sender.
            senderreceiver_sender_self[0]->_lf__reaction_3.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 3 of senderreceiver.sender
        
        }
        // **** End of deferred initialize for senderreceiver.sender
        // **** Start deferred initialize for senderreceiver.receiver
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of senderreceiver.receiver.
            senderreceiver_receiver_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of senderreceiver.receiver
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of senderreceiver.receiver.
            senderreceiver_receiver_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of senderreceiver.receiver
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of senderreceiver.receiver.
            senderreceiver_receiver_self[0]->_lf__reaction_2.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 2 of senderreceiver.receiver
        
        }
        // **** End of deferred initialize for senderreceiver.receiver
    }
    // **** End of deferred initialize for senderreceiver
    // **** Start non-nested deferred initialize for senderreceiver
    {
    
    
    
        // **** Start non-nested deferred initialize for senderreceiver.bitGenerator
        {
        
            // For reference counting, set num_destinations for port senderreceiver.bitGenerator.out.
            // Iterate over range senderreceiver.bitGenerator.out(0,1)->[senderreceiver.sender.in(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                senderreceiver_bitgenerator_self[src_runtime]->_lf_out._base.num_destinations = 1;
                senderreceiver_bitgenerator_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)senderreceiver_bitgenerator_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range senderreceiver.bitGenerator.out(0,1)->[senderreceiver.sender.in(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of senderreceiver.bitGenerator triggers 1 downstream reactions
                    // through port senderreceiver.bitGenerator.out.
                    senderreceiver_bitgenerator_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of senderreceiver.bitGenerator, allocate an
                    // array of trigger pointers for downstream reactions through port senderreceiver.bitGenerator.out
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &senderreceiver_bitgenerator_self[src_runtime]->base.allocations); 
                    senderreceiver_bitgenerator_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges senderreceiver.bitGenerator.out(0,1)->[senderreceiver.sender.in(0,1)] and senderreceiver.sender.in(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range senderreceiver.sender.in(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port senderreceiver.sender.in's trigger struct.
                        senderreceiver_bitgenerator_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &senderreceiver_sender_self[dst_runtime]->_lf__in;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for senderreceiver.bitGenerator
        // **** Start non-nested deferred initialize for senderreceiver.sender
        {
        
            // For reference counting, set num_destinations for port senderreceiver.sender.up.
            // Iterate over range senderreceiver.sender.up(0,1)->[senderreceiver.receiver.up(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                senderreceiver_sender_self[src_runtime]->_lf_up._base.num_destinations = 1;
                senderreceiver_sender_self[src_runtime]->_lf_up._base.source_reactor = (self_base_t*)senderreceiver_sender_self[src_runtime];
            }
            for (int index486184027c8990b = 0; index486184027c8990b < 1; index486184027c8990b++) { senderreceiver_sender_self[0]->_lf_down._base.source_reactor = (self_base_t*)senderreceiver_sender_self[0]; }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range senderreceiver.sender.up(0,1)->[senderreceiver.receiver.up(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 2 of senderreceiver.sender triggers 1 downstream reactions
                    // through port senderreceiver.sender.up.
                    senderreceiver_sender_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 2 of senderreceiver.sender, allocate an
                    // array of trigger pointers for downstream reactions through port senderreceiver.sender.up
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &senderreceiver_sender_self[src_runtime]->base.allocations); 
                    senderreceiver_sender_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges senderreceiver.sender.up(0,1)->[senderreceiver.receiver.up(0,1)] and senderreceiver.receiver.up(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range senderreceiver.receiver.up(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port senderreceiver.receiver.up's trigger struct.
                        senderreceiver_sender_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &senderreceiver_receiver_self[dst_runtime]->_lf__up;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for senderreceiver.sender
        // **** Start non-nested deferred initialize for senderreceiver.receiver
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for senderreceiver.receiver
    }
    // **** End of non-nested deferred initialize for senderreceiver
    // Connect inputs and outputs for reactor senderreceiver.
    // Connect inputs and outputs for reactor senderreceiver.bitGenerator.
    // Connect senderreceiver.bitGenerator.out(0,1)->[senderreceiver.sender.in(0,1)] to port senderreceiver.sender.in(0,1)
    // Iterate over ranges senderreceiver.bitGenerator.out(0,1)->[senderreceiver.sender.in(0,1)] and senderreceiver.sender.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range senderreceiver.sender.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            senderreceiver_sender_self[dst_runtime]->_lf_in = (_sendermodel_in_t*)&senderreceiver_bitgenerator_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor senderreceiver.sender.
    // Connect senderreceiver.sender.up(0,1)->[senderreceiver.receiver.up(0,1)] to port senderreceiver.receiver.up(0,1)
    // Iterate over ranges senderreceiver.sender.up(0,1)->[senderreceiver.receiver.up(0,1)] and senderreceiver.receiver.up(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range senderreceiver.receiver.up(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            senderreceiver_receiver_self[dst_runtime]->_lf_up = (_receivermodel_up_t*)&senderreceiver_sender_self[src_runtime]->_lf_up;
        }
    }
    
    // Connect inputs and outputs for reactor senderreceiver.receiver.
    {
    }
    {
        // Add action senderreceiver.sender.a to array of is_present fields.
        envs[senderreceiver_main].is_present_fields[0 + (0) * 1]
                = (bool *) &senderreceiver_sender_self[0]->_lf__a.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action senderreceiver.sender.a to array of intended_tag fields.
        envs[senderreceiver_main]._lf_intended_tag_fields[0 + (0) * 1]
                = &senderreceiver_sender_self[0]->_lf_a.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action senderreceiver.receiver.a to array of is_present fields.
        envs[senderreceiver_main].is_present_fields[1 + (0) * 1]
                = (bool *) &senderreceiver_receiver_self[0]->_lf__a.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action senderreceiver.receiver.a to array of intended_tag fields.
        envs[senderreceiver_main]._lf_intended_tag_fields[1 + (0) * 1]
                = &senderreceiver_receiver_self[0]->_lf_a.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port senderreceiver.bitGenerator.out to array of is_present fields.
            envs[senderreceiver_main].is_present_fields[(0) * 1 + 2 + count] = &senderreceiver_bitgenerator_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port senderreceiver.bitGenerator.out to array of intended_tag fields.
            envs[senderreceiver_main]._lf_intended_tag_fields[(0) * 1 + 2 + count] = &senderreceiver_bitgenerator_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port senderreceiver.sender.up to array of is_present fields.
            envs[senderreceiver_main].is_present_fields[(0) * 2 + 3 + count] = &senderreceiver_sender_self[0]->_lf_up.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port senderreceiver.sender.up to array of intended_tag fields.
            envs[senderreceiver_main]._lf_intended_tag_fields[(0) * 2 + 3 + count] = &senderreceiver_sender_self[0]->_lf_up.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add output port senderreceiver.sender.down to array of is_present fields.
            envs[senderreceiver_main].is_present_fields[(0) * 2 + 3 + count] = &senderreceiver_sender_self[0]->_lf_down.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port senderreceiver.sender.down to array of intended_tag fields.
            envs[senderreceiver_main]._lf_intended_tag_fields[(0) * 2 + 3 + count] = &senderreceiver_sender_self[0]->_lf_down.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance senderreceiver
    {
    
        // Set reaction priorities for ReactorInstance senderreceiver.bitGenerator
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_bitgenerator_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance senderreceiver.sender
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_sender_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_sender_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_sender_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 2);
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_sender_self[0]->_lf__reaction_3.index = lf_combine_deadline_and_level(9223372036854775807, 3);
        }
    
    
        // Set reaction priorities for ReactorInstance senderreceiver.receiver
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_receiver_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_receiver_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 3);
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            senderreceiver_receiver_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 4);
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[5] = 
        {3, 1, 1, 2, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 5};
    lf_sched_init(
        &envs[senderreceiver_main],
        envs[senderreceiver_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
